services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: taisaovayem
      WORDPRESS_DB_PASSWORD: 36f&DIus1]$,
      WORDPRESS_DB_NAME: taisaovayem
    volumes:
      - ./wordpress-data/wp-content:/var/www/html/wp-content
      - ./wordpress-data/config/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: taisaovayem
      MYSQL_USER: taisaovayem
      MYSQL_PASSWORD: 36f&DIus1]$,
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
  wordpress:
  db:
